"""Initial migration full schema

Revision ID: 2a242b466592
Revises: 
Create Date: 2025-11-22 12:08:18.225536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a242b466592'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('client_secret', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('auto_approve', sa.Boolean(), nullable=True),
    sa.Column('icon_filename', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banks_id'), 'banks', ['id'], unique=False)
    op.create_index(op.f('ix_banks_name'), 'banks', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='f', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('connected_banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('bank_client_id', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('consent_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consent_id')
    )
    op.create_index(op.f('ix_connected_banks_bank_client_id'), 'connected_banks', ['bank_client_id'], unique=False)
    op.create_index(op.f('ix_connected_banks_bank_name'), 'connected_banks', ['bank_name'], unique=False)
    op.create_index(op.f('ix_connected_banks_id'), 'connected_banks', ['id'], unique=False)
    op.create_index(op.f('ix_connected_banks_request_id'), 'connected_banks', ['request_id'], unique=True)
    op.create_table('payment_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('bank_client_id', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('consent_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consent_id')
    )
    op.create_index(op.f('ix_payment_consents_bank_client_id'), 'payment_consents', ['bank_client_id'], unique=False)
    op.create_index(op.f('ix_payment_consents_bank_name'), 'payment_consents', ['bank_name'], unique=False)
    op.create_index(op.f('ix_payment_consents_id'), 'payment_consents', ['id'], unique=False)
    op.create_index(op.f('ix_payment_consents_request_id'), 'payment_consents', ['request_id'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('api_account_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('account_subtype', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('opening_date', sa.String(), nullable=True),
    sa.Column('statement_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('owner_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('balance_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connected_banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_api_account_id'), 'accounts', ['api_account_id'], unique=False)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('debtor_account_id', sa.Integer(), nullable=False),
    sa.Column('consent_id', sa.Integer(), nullable=False),
    sa.Column('bank_payment_id', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('bank_client_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('creditor_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['consent_id'], ['payment_consents.id'], ),
    sa.ForeignKeyConstraint(['debtor_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_payments_bank_payment_id'), 'payments', ['bank_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('scheduled_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('debtor_account_id', sa.Integer(), nullable=False),
    sa.Column('creditor_account_id', sa.Integer(), nullable=False),
    sa.Column('next_payment_date', sa.Date(), nullable=False),
    sa.Column('period_start_date', sa.Date(), nullable=True),
    sa.Column('period_end_date', sa.Date(), nullable=True),
    sa.Column('recurrence_type', sa.Enum('DAYS', 'WEEKS', 'MONTHS', 'YEARS', name='recurrencetype'), nullable=True),
    sa.Column('recurrence_interval', sa.Integer(), nullable=True),
    sa.Column('amount_type', sa.Enum('FIXED', 'TOTAL_DEBIT', 'NET_DEBIT', 'MINIMUM_PAYMENT', name='scheduledpaymentamounttype'), nullable=False),
    sa.Column('fixed_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('minimum_payment_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creditor_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['debtor_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_payments_id'), 'scheduled_payments', ['id'], unique=False)
    op.create_index(op.f('ix_scheduled_payments_next_payment_date'), 'scheduled_payments', ['next_payment_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_payments_next_payment_date'), table_name='scheduled_payments')
    op.drop_index(op.f('ix_scheduled_payments_id'), table_name='scheduled_payments')
    op.drop_table('scheduled_payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_bank_payment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_api_account_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_payment_consents_request_id'), table_name='payment_consents')
    op.drop_index(op.f('ix_payment_consents_id'), table_name='payment_consents')
    op.drop_index(op.f('ix_payment_consents_bank_name'), table_name='payment_consents')
    op.drop_index(op.f('ix_payment_consents_bank_client_id'), table_name='payment_consents')
    op.drop_table('payment_consents')
    op.drop_index(op.f('ix_connected_banks_request_id'), table_name='connected_banks')
    op.drop_index(op.f('ix_connected_banks_id'), table_name='connected_banks')
    op.drop_index(op.f('ix_connected_banks_bank_name'), table_name='connected_banks')
    op.drop_index(op.f('ix_connected_banks_bank_client_id'), table_name='connected_banks')
    op.drop_table('connected_banks')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_banks_name'), table_name='banks')
    op.drop_index(op.f('ix_banks_id'), table_name='banks')
    op.drop_table('banks')
    # ### end Alembic commands ###
