"""Add scheduled_payments table

Revision ID: 6f4b0f226ba2
Revises: d0bda690b79d
Create Date: 2025-11-17 19:36:24.013233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f4b0f226ba2'
down_revision: Union[str, Sequence[str], None] = 'd0bda690b79d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('debtor_account_id', sa.Integer(), nullable=False),
    sa.Column('creditor_account_id', sa.Integer(), nullable=False),
    sa.Column('payment_day_of_month', sa.Integer(), nullable=False),
    sa.Column('statement_day_of_month', sa.Integer(), nullable=False),
    sa.Column('amount_type', sa.Enum('FIXED', 'TOTAL_DEBIT', 'NET_DEBIT', name='scheduledpaymentamounttype'), nullable=False),
    sa.Column('fixed_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creditor_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['debtor_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_payments_id'), 'scheduled_payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_payments_id'), table_name='scheduled_payments')
    op.drop_table('scheduled_payments')
    # ### end Alembic commands ###
